<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-03-08T18:36:56+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'TERREK',
    'version_installed' => '5.7.5.6',
    'misc' => array(
        'access_entity_updated' => 1457291413,
        'latest_version' => '5.7.5.6',
        'do_page_reindex_check' => false,
    ),
);
